### ISSUE TITLE
如果选择了 nasconfig: auto  的写法， vpc 也会自动创建， 不需要单独在 yml 中手动填写 vpc 配置

### ISSUE THREAD

**Issue by rsonghuster** [devsapp/start-puppeteer#5] opened 2021-08-10 10:05 UTC
![image](https://user-images.githubusercontent.com/10919599/128848463-bd781fce-1f68-440d-b81a-7bbf4f73f45b.png)

![image](https://user-images.githubusercontent.com/10919599/128848708-40279af9-be11-4db2-b51e-1aa2f972fd17.png)

**Comment by alapha23** [comment] 2021-08-10 13:33
Thank you for pointing it out.
The issue is addressed in PR [Fix nodejs vpc config and container directory orders](https://github.com/devsapp/start-puppeteer/pull/6). It would be nice if you could review it. TIA.

**Closed** 2021-08-12 08:13 UTC
